### ISSUE TITLE
kwicks intermittently overflowing container

### ISSUE THREAD

**Issue by jewells** [jmar777/kwicks#33] opened 2013-10-15 19:23 UTC
On some initialization of page the individual panels are opening wider causing overflow of containing div. The last panel is fixed to the end of the div and the last but one is pushing out under and past last.

I have 6 panels with 5px space in 1000px div. Normal closed size of panels is 162 or 163 and size when error occurs is about 218 or 219.

http://jewells-webhost.co.uk/adrianbird/kitchens.html 

Any help please ?

**Comment by jmar777** [comment] 2013-10-16 13:54
Hey - what browser are you seeing that behavior in? I'm not able to reproduce it on my end (running Chrome 30.0.1599.69 on OS X).

**Comment by jewells** [comment] 2013-10-16 15:45
Hi  
Thanks for getting back to me.
It was happening in Chrome, Saffari and Firefox but I think I may have stopped it.
The div containing the kwicks ul  had a width set to 1000px in a css file linked to by the page after the script in head section. Have added the width 1000px to the class kwicks in the kwicks css file and this seems to have solved it..

**Comment by jmar777** [comment] 2013-10-17 13:59
Glad it's working!  And yes, if you were running the Kwicks plugin prior to loading the associated CSS, then I would expect weird behavior.  I'm going to close this issue since it's behaving now, but feel free to re-open or open a new one if you run into any more strange behavior.

**Closed as completed by jmar777** 2013-10-17 13:59 UTC
